In [83]:
#Import libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.preprocessing import MinMaxScaler 
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

pd.reset_option("display.max_rows")

#Import data
data = pd.read_csv('fifa21_train.csv')
data


ID            Name  Age  Nationality                        Club  \
0      184383       A. Pasche   26  Switzerland           FC Lausanne-Sport   
1      188044   Alan Carvalho   30     China PR     Beijing Sinobo Guoan FC   
2      184431     S. Giovinco   33        Italy                    Al Hilal   
3      233796        J. Evans   22        Wales                Swansea City   
4      234799      Y. Demoncy   23       France  US Orléans Loiret Football   
...       ...             ...  ...          ...                         ...   
11696  232504   B. Böðvarsson   25      Iceland       Jagiellonia Białystok   
11697  214680       G. Gallon   27       France                ESTAC Troyes   
11698  221489       J. Flores   22        Chile              CD Antofagasta   
11699  146717  Anderson Silva   26       Brazil                    Barnsley   
11700  236507     T. Conechny   22    Argentina            Portland Timbers   

        BP   Position                               Team & Contract Height  \
0       CM     CM CDM                 FC Lausanne-Sport 2015 ~ 2020   5'9"   
1       ST   ST LW LM  Beijing Sinobo Guoan FC Dec 31, 2020 On Loan   6'0"   
2      CAM     CAM CF                          Al Hilal 2019 ~ 2022   5'4"   
3      CDM     CDM CM                      Swansea City 2016 ~ 2021  5'10"   
4      CDM     CDM CM        US Orléans Loiret Football 2018 ~ 2021  5'11"   
...    ...        ...                                           ...    ...   
11696   LB         LB             Jagiellonia Białystok 2018 ~ 2021   6'1"   
11697   GK         GK                      ESTAC Troyes 2019 ~ 2022   6'1"   
11698   RM  LM CAM RM                    CD Antofagasta 2019 ~ 2024   5'6"   
11699   CM        NaN                                 Barnsley 2010   6'2"   
11700  CAM  ST CAM LM                  Portland Timbers 2019 ~ 2020   5'7"   

       Weight  ...   CDM   RDM   RWB    LB   LCB    CB   RCB    RB    GK  OVA  
0      161lbs  ...  59+1  59+1  59+1  58+1  54+1  54+1  54+1  58+1  15+1   64  
1      159lbs  ...  53+2  53+2  57+2  53+2  48+2  48+2  48+2  53+2  18+2   77  
2      134lbs  ...  56+2  56+2  59+2  53+2  41+2  41+2  41+2  53+2  12+2   80  
3      152lbs  ...  58+2  58+2  56+2  57+2  58+2  58+2  58+2  57+2  14+2   59  
4      150lbs  ...  64+2  64+2  64+2  63+2  61+2  61+2  61+2  63+2  15+2   65  
...       ...  ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...  
11696  168lbs  ...  60+2  60+2  63+2  63+2  61+2  61+2  61+2  63+2  16+2   65  
11697  174lbs  ...  26+2  26+2  25+2  24+2  26+2  26+2  26+2  24+2  69+2   70  
11698  143lbs  ...  44+2  44+2  49+2  45+2  35+2  35+2  35+2  45+2  17+2   67  
11699  179lbs  ...  68+0  68+0  66+0  64+0  60+0  60+0  60+0  64+0  25+0   68  
11700  143lbs  ...  43+2  43+2  46+2  44+2  36+2  36+2  36+2  44+2  15+2   64  

[11701 rows x 101 columns]

<span style="font-size: 200%;">Cleaning Data</span>

In [84]:
# Cleaning Data: do we want to change columns names - no we prefer understanding the data content

#check for duplicates
data = data.drop_duplicates()
data

ID            Name  Age  Nationality                        Club  \
0      184383       A. Pasche   26  Switzerland           FC Lausanne-Sport   
1      188044   Alan Carvalho   30     China PR     Beijing Sinobo Guoan FC   
2      184431     S. Giovinco   33        Italy                    Al Hilal   
3      233796        J. Evans   22        Wales                Swansea City   
4      234799      Y. Demoncy   23       France  US Orléans Loiret Football   
...       ...             ...  ...          ...                         ...   
11696  232504   B. Böðvarsson   25      Iceland       Jagiellonia Białystok   
11697  214680       G. Gallon   27       France                ESTAC Troyes   
11698  221489       J. Flores   22        Chile              CD Antofagasta   
11699  146717  Anderson Silva   26       Brazil                    Barnsley   
11700  236507     T. Conechny   22    Argentina            Portland Timbers   

        BP   Position                               Team & Contract Height  \
0       CM     CM CDM                 FC Lausanne-Sport 2015 ~ 2020   5'9"   
1       ST   ST LW LM  Beijing Sinobo Guoan FC Dec 31, 2020 On Loan   6'0"   
2      CAM     CAM CF                          Al Hilal 2019 ~ 2022   5'4"   
3      CDM     CDM CM                      Swansea City 2016 ~ 2021  5'10"   
4      CDM     CDM CM        US Orléans Loiret Football 2018 ~ 2021  5'11"   
...    ...        ...                                           ...    ...   
11696   LB         LB             Jagiellonia Białystok 2018 ~ 2021   6'1"   
11697   GK         GK                      ESTAC Troyes 2019 ~ 2022   6'1"   
11698   RM  LM CAM RM                    CD Antofagasta 2019 ~ 2024   5'6"   
11699   CM        NaN                                 Barnsley 2010   6'2"   
11700  CAM  ST CAM LM                  Portland Timbers 2019 ~ 2020   5'7"   

       Weight  ...   CDM   RDM   RWB    LB   LCB    CB   RCB    RB    GK  OVA  
0      161lbs  ...  59+1  59+1  59+1  58+1  54+1  54+1  54+1  58+1  15+1   64  
1      159lbs  ...  53+2  53+2  57+2  53+2  48+2  48+2  48+2  53+2  18+2   77  
2      134lbs  ...  56+2  56+2  59+2  53+2  41+2  41+2  41+2  53+2  12+2   80  
3      152lbs  ...  58+2  58+2  56+2  57+2  58+2  58+2  58+2  57+2  14+2   59  
4      150lbs  ...  64+2  64+2  64+2  63+2  61+2  61+2  61+2  63+2  15+2   65  
...       ...  ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...  
11696  168lbs  ...  60+2  60+2  63+2  63+2  61+2  61+2  61+2  63+2  16+2   65  
11697  174lbs  ...  26+2  26+2  25+2  24+2  26+2  26+2  26+2  24+2  69+2   70  
11698  143lbs  ...  44+2  44+2  49+2  45+2  35+2  35+2  35+2  45+2  17+2   67  
11699  179lbs  ...  68+0  68+0  66+0  64+0  60+0  60+0  60+0  64+0  25+0   68  
11700  143lbs  ...  43+2  43+2  46+2  44+2  36+2  36+2  36+2  44+2  15+2   64  

[11701 rows x 101 columns]

In [85]:
print(data.columns.tolist())

['ID', 'Name', 'Age', 'Nationality', 'Club', 'BP', 'Position', 'Team & Contract', 'Height', 'Weight', 'foot', 'Growth', 'Joined', 'Loan Date End', 'Value', 'Wage', 'Release Clause', 'Contract', 'Attacking', 'Crossing', 'Finishing', 'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling', 'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement', 'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance', 'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots', 'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle', 'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling', 'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats', 'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY', 'Hits', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW', 'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM', 'CDM', 'RDM', 'RWB'

In [86]:
import numpy as np

#checking For nan values
nan_counts = data.isna().sum()

nan_columns = nan_counts[nan_counts>0]
nan_columns

Club                 18
Position            288
Joined               41
Loan Date End     11072
Volleys              41
Curve                41
Agility              41
Balance              41
Jumping              41
Interceptions         7
Positioning           7
Vision               41
Composure           279
Sliding Tackle       41
A/W                  59
D/W                  59
dtype: int64

In [87]:
# Dropping loan data end columns as it has a high number of NaN values.
data = data.drop('Loan Date End', axis=1)

In [88]:
data['Volleys']

0        44.0
1        76.0
2        75.0
3        36.0
4        34.0
         ... 
11696    28.0
11697    16.0
11698    41.0
11699     NaN
11700    53.0
Name: Volleys, Length: 11701, dtype: float64

In [89]:
data.dtypes

ID              int64
Name           object
Age             int64
Nationality    object
Club           object
                ...  
CB             object
RCB            object
RB             object
GK             object
OVA             int64
Length: 100, dtype: object

In [90]:
data.dropna(subset = ['Volleys'], inplace=True)

In [91]:
#checking for columns NaN values
nan_counts = data.isna().sum()
nan_columns = nan_counts[nan_counts>0]
nan_columns

Club          14
Position     274
Composure    238
A/W           18
D/W           18
dtype: int64

In [92]:
#NaN values in the A/W column
nan_aw_rows= data[data['A/W'].isna()]
nan_aw_rows

ID                Name  Age  Nationality                 Club   BP  \
409       496           D. Hamann   36      Germany   Milton Keynes Dons   CB   
1336   158320       Dong Fangzhuo   25     China PR      Portimonense SC   ST   
2398      670                Zulu   26       Brazil      Pohang Steelers   ST   
2573   177609         L. García B   24       Mexico          Club Necaxa   RB   
3202     1668         C. Makélelé   37       France  Paris Saint-Germain  CDM   
3239    51539      E. van der Sar   39  Netherlands    Manchester United   GK   
3987   166087           A. Karimi   31         Iran        FC Schalke 04   RM   
4570     1419           P. Vieira   34       France      Manchester City  CDM   
4805   139009          J. Beltrán   33       Mexico            Querétaro   CB   
5293   193518       B. Tshibuabua   18     DR Congo         Beerschot AC   ST   
5752   111016               Mista   31        Spain           Toronto FC   ST   
6063   143618  Serhat Akin RF  LF   29       Turkey        Karlsruher SC   RW   
7098   191008              B. Gan   22    Australia            Sydney FC   RW   
8529    52582           R. Reçber   37       Turkey          Beşiktaş JK   GK   
8605   201918         Victor Hugo   19       Brazil               Santos   RW   
9931   188790          S. Mehamha   19       France   Olympique Lyonnais  CDM   
10335  138292           P. Onstad   42       Canada            DC United   GK   
11338    5673         J. Litmanen   39      Finland              Finland  CAM   

           Position                  Team & Contract Height  Weight  ...  \
409             NaN   Milton Keynes Dons 2010 ~ 2011   6'2"  168lbs  ...   
1336          CF ST      Portimonense SC 2005 ~ 2012   6'2"  163lbs  ...   
2398            NaN      Pohang Steelers 2005 ~ 2013   6'4"  198lbs  ...   
2573            NaN          Club Necaxa 2005 ~ 2011  5'10"  157lbs  ...   
3202         CDM CM  Paris Saint-Germain 2008 ~ 2011   5'9"  154lbs  ...   
3239             GK    Manchester United 2005 ~ 2011   6'6"  196lbs  ...   
3987            NaN        FC Schalke 04 2011 ~ 2011  5'10"  172lbs  ...   
4570         CDM CM      Manchester City 2010 ~ 2011   6'4"  181lbs  ...   
4805            NaN            Querétaro 2009 ~ 2011   6'2"  201lbs  ...   
5293          ST CF         Beerschot AC 2009 ~ 2013  5'10"  157lbs  ...   
5752             ST           Toronto FC 2010 ~ 2013   6'0"  163lbs  ...   
6063            NaN        Karlsruher SC 2009 ~ 2011  5'10"  163lbs  ...   
7098   CAM RM CM ST            Sydney FC 2009 ~ 2011  5'10"  150lbs  ...   
8529             GK          Beşiktaş JK 2007 ~ 2012   6'2"  168lbs  ...   
8605         CAM CF               Santos 2010 ~ 2011   5'5"  139lbs  ...   
9931         CDM CM   Olympique Lyonnais 2008 ~ 2011   5'7"  143lbs  ...   
10335           NaN            DC United 2005 ~ 2011   6'4"  216lbs  ...   
11338           NaN                     Finland Free  5'11"  176lbs  ...   

        CDM   RDM   RWB    LB   LCB    CB   RCB    RB    GK  OVA  
409    65+0  65+0  58+0  62+0  67+0  67+0  67+0  62+0  14+0   61  
1336   48+0  48+0  48+0  46+0  46+0  46+0  46+0  46+0  10+0   62  
2398   54+0  54+0  51+0  51+0  54+0  54+0  54+0  51+0  16+0   66  
2573   61+0  61+0  62+0  62+0  62+0  62+0  62+0  62+0  15+0   62  
3202   74+0  74+0  70+0  72+0  73+0  73+0  73+0  72+0  12+0   74  
3239   31+0  31+0  25+0  27+0  29+0  29+0  29+0  27+0  83+0   83  
3987   55+0  55+0  53+0  48+0  45+0  45+0  45+0  48+0  12+0   73  
4570   76+0  76+0  72+0  75+0  77+0  77+0  77+0  75+0  16+0   76  
4805   66+0  66+0  63+0  65+0  68+0  68+0  68+0  65+0  15+0   68  
5293   47+0  47+0  48+0  45+0  45+0  45+0  45+0  45+0  14+0   61  
5752   53+0  53+0  52+0  50+0  50+0  50+0  50+0  50+0  15+0   68  
6063   50+0  50+0  50+0  46+0  45+0  45+0  45+0  46+0  16+0   65  
7098   42+0  42+0  43+0  37+0  32+0  32+0  32+0  37+0  12+0   57  
8529   30+0  30+0  24+0  27+0  30+0  30+0  30+0  27+0  73+0   73  
8605   51+0  51+0  51

In [93]:
#dropping NaN values in the A/W column
data.dropna(subset = ['A/W'], inplace=True)

#checking for NaN values again
nan_counts = data.isna().sum()
nan_columns = nan_counts[nan_counts>0]
nan_columns

Club          14
Position     266
Composure    220
dtype: int64

In [94]:
nan_aw_club= data[data['Club'].isna()]
nan_aw_club

ID               Name  Age           Nationality Club   BP  \
102     31432          D. Drogba   38           Ivory Coast  NaN   ST   
535    121944  B. Schweinsteiger   34               Germany  NaN   CB   
697    251744          A. Grewal   26                 India  NaN   ST   
1599   247059      A. Al Hidhani   22  United Arab Emirates  NaN   RB   
1754     1625           T. Henry   36                France  NaN  CAM   
2224   138449               Kaká   35                Brazil  NaN  CAM   
2342   251737          J. Mangat   26                 India  NaN   LM   
5331   251734          A. Sanghu   20                 India  NaN   RM   
5591   251740         G. Thakkar   23                 India  NaN   RM   
7809   247066     H. Al Mansoury   24  United Arab Emirates  NaN   GK   
8341   231577         O. Morales   27               Bolivia  NaN  RWB   
10228  251738           M. Chada   27                 India  NaN   RM   
11159  193911            S. Paul   31                 India  NaN   GK   
11509     250         D. Beckham   37               England  NaN   CM   

           Position            Team & Contract Height  Weight  ...   CDM  \
102              ST           Ivory Coast Free   6'2"  176lbs  ...  55+2   
535              CB               Germany Free   6'0"  174lbs  ...  75+0   
697        ST RM LM                 India Free   5'8"  148lbs  ...  37+2   
1599             RB  United Arab Emirates Free   5'8"  148lbs  ...  50+2   
1754   CF ST CAM LW                France Free   6'2"  183lbs  ...  57+1   
2224         CAM CF                Brazil Free   6'1"  183lbs  ...  56+2   
2342             LM                 India Free   5'7"  143lbs  ...  34+2   
5331          RM CM                 India Free   5'6"  137lbs  ...  42+2   
5591             ST                 India Free  5'10"  174lbs  ...  42+2   
7809             GK  United Arab Emirates Free  5'10"  161lbs  ...  21+2   
8341             RB               Bolivia Free  5'11"  176lbs  ...  56+0   
10228            ST                 India Free  5'10"  170lbs  ...  46+2   
11159            GK                 India Free   6'1"  172lbs  ...  24+1   
11509         CM RM               England Free   6'0"  165lbs  ...  73+1   

        RDM    RWB    LB   LCB    CB   RCB    RB    GK  OVA  
102    55+2   55+2  53+2  53+2  53+2  53+2  53+2  18+2   81  
535    75+0   68+3  68+3  73+2  73+2  73+2  68+3  20+3   75  
697    37+2   40+2  39+2  36+2  36+2  36+2  39+2  14+2   54  
1599   50+2   54+2  54+2  52+2  52+2  52+2  54+2  15+2   56  
1754   57+1   54+1  48+1  45+1  45+1  45+1  48+1  15+1   79  
2224   56+2   55+2  51+2  45+2  45+2  45+2  51+2  12+2   80  
2342   34+2   39+2  37+2  31+2  31+2  31+2  37+2  13+2   53  
5331   42+2   47+2  46+2  37+2  37+2  37+2  46+2  15+2   56  
5591   42+2   45+2  44+2  38+2  38+2  38+2  44+2  16+2   58  
7809   21+2   20+2  20+2  20+2  20+2  20+2  20+2  57+2   58  
8341   56+0  60+-1  59+0  56+0  56+0  56+0  59+0  13+0   59  
10228  46+2   48+2  47+2  42+2  42+2  42+2  47+2  15+2   55  
11159  24+1   25+1  25+1  23+1  23+1  23+1  25+1  56+1   57  
11509  73+1   67+1  63+1  59+1  59+1  59+1  63+1  15+1   78  

[14 rows x 100 columns]

In [95]:
#Replacing club NaN values with a new category Unknown/Retired

data['Club'].fillna('Unknown/Retired', inplace= True)

#checking for nan values
nan_counts = data.isna().sum()

nan_columns = nan_counts[nan_counts>0]
nan_columns

Position     266
Composure    220
dtype: int64

In [96]:
nan_aw_rows= data[data['Position'].isna()]
nan_aw_rows

ID         Name  Age          Nationality             Club  BP  \
17       5203    M. Oddo B   35                Italy            Lecce  CM   
59     152107    P. Netzer   34              Austria       SCR Altach  CB   
132    157734  A. Jaakkola   33              Finland   Bristol Rovers  GK   
157    165509    B. Clarke   32  Republic of Ireland    Bradford City  ST   
214    145020         Mora   37                Spain        Getafe CF  CM   
...       ...          ...  ...                  ...              ...  ..   
11101  158394   K. Reichel   33              Germany    VfL Osnabrück  LB   
11265  101015  N. Castillo   29               Mexico   Rayo Vallecano  LW   
11350  169862  F. Eastwood   29                Wales  Southend United  ST   
11580  146692         Nenê   32               Brazil  West Ham United  LW   
11670   54037     T. Berni   37                Italy            Inter  GK   

      Position              Team & Contract Height  Weight  ...   CDM   RDM  \
17         NaN            Lecce 2009 ~ 2012   6'0"  168lbs  ...  71+0  71+0   
59         NaN       SCR Altach 2004 ~ 2021   6'2"  176lbs  ...  63+2  63+2   
132        NaN   Bristol Rovers 2019 ~ 2022   6'4"  194lbs  ...  30+2  30+2   
157        NaN    Bradford City 2020 ~ 2021   5'7"  141lbs  ...  47+2  47+2   
214        NaN        Getafe CF 2017 ~ 2021   6'0"  161lbs  ...  69+1  69+1   
...        ...                          ...    ...     ...  ...   ...   ...   
11101      NaN    VfL Osnabrück 2020 ~ 2021   6'1"  185lbs  ...  67+2  67+2   
11265      NaN   Rayo Vallecano 2013 ~ 2014   5'7"  134lbs  ...  51+0  51+0   
11350      NaN  Southend United 2012 ~ 2014  5'11"  172lbs  ...  46+0  46+0   
11580      NaN  West Ham United 2015 ~ 2015  5'11"  154lbs  ...  59+0  59+0   
11670      NaN            Inter 2017 ~ 2020   6'1"  176lbs  ...  22+2  22+2   

         RWB    LB   LCB    CB   RCB    RB    GK  OVA  
17     72+-1  70+1  70+1  70+1  70+1  70+1  14+1   71  
59      58+2  59+2  65+0  65+0  65+0  59+2  15+2   65  
132     27+2  27+2  28+2  28+2  28+2  27+2  66+1   67  
157     49+2  47+2  48+2  48+2  48+2  47+2  16+2   63  
214     62+1  60+1  62+1  62+1  62+1  60+1  17+1   70  
...      ...   ...   ...   ...   ...   ...   ...  ...  
11101   68+1  67+2  68+1  68+1  68+1  67+2  16+2   69  
11265   51+0  47+0  44+0  44+0  44+0  47+0  15+0   68  
11350   47+0  42+0  40+0  40+0  40+0  42+0  16+0   60  
11580   55+0  50+0  46+0  46+0  46+0  50+0  13+0   76  
11670   20+2  19+2  19+2  19+2  19+2  19+2  63+1   64  

[266 rows x 100 columns]

In [97]:
#Replacing the NaN position values with the same value in the BP column

data['Position'].fillna(data['BP'], inplace= True)

#checking fro nan values
nan_counts = data.isna().sum()

nan_columns = nan_counts[nan_counts>0]
nan_columns

Composure    220
dtype: int64

In [98]:
data['Composure'].mean()

59.94773244615654

In [99]:
#filling in the average composure of each player. NaN is replaces with the mean value of players who play in the same position. (mean is categorised into each position, players who play in the same BP, then the composure of those is calculated and used to replace the NaN values )
data['Composure'] = data.groupby('BP')['Composure'].transform(lambda x: x.fillna(x.mean()))

#checking for nan values
nan_counts = data.isna().sum()

nan_columns = nan_counts[nan_counts>0]
nan_columns

Series([], dtype: int64)

<span style="font-size: 200%;">Defining categorical and numerical columns</span>

In [100]:
# replaing + - signs in columns

position_columns = ['LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW', 'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 
                     'RM', 'LWB', 'LDM', 'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'GK']
for column in position_columns:
    data[column] = data[column].str.extract(r'(\d{2})').astype(float)

In [101]:
data.head()

ID           Name  Age  Nationality                        Club   BP  \
0  184383      A. Pasche   26  Switzerland           FC Lausanne-Sport   CM   
1  188044  Alan Carvalho   30     China PR     Beijing Sinobo Guoan FC   ST   
2  184431    S. Giovinco   33        Italy                    Al Hilal  CAM   
3  233796       J. Evans   22        Wales                Swansea City  CDM   
4  234799     Y. Demoncy   23       France  US Orléans Loiret Football  CDM   

   Position                               Team & Contract Height  Weight  ...  \
0    CM CDM                 FC Lausanne-Sport 2015 ~ 2020   5'9"  161lbs  ...   
1  ST LW LM  Beijing Sinobo Guoan FC Dec 31, 2020 On Loan   6'0"  159lbs  ...   
2    CAM CF                          Al Hilal 2019 ~ 2022   5'4"  134lbs  ...   
3    CDM CM                      Swansea City 2016 ~ 2021  5'10"  152lbs  ...   
4    CDM CM        US Orléans Loiret Football 2018 ~ 2021  5'11"  150lbs  ...   

    CDM   RDM   RWB    LB   LCB    CB   RCB    RB    GK  OVA  
0  59.0  59.0  59.0  58.0  54.0  54.0  54.0  58.0  15.0   64  
1  53.0  53.0  57.0  53.0  48.0  48.0  48.0  53.0  18.0   77  
2  56.0  56.0  59.0  53.0  41.0  41.0  41.0  53.0  12.0   80  
3  58.0  58.0  56.0  57.0  58.0  58.0  58.0  57.0  14.0   59  
4  64.0  64.0  64.0  63.0  61.0  61.0  61.0  63.0  15.0   65  

[5 rows x 100 columns]

In [102]:
#changing the height from ft and inches to cm

def height_to_cm(height_str):
    #split the numbers to separate feet from inches
    feet, inches = height_str.split("\'")
    
    feet=int(feet)
    inches= int(inches.replace('\"',""))
    
    #conversion
    total_inches = (feet*12)+inches
    return total_inches*2.54

data['Height'] =data['Height'].apply(height_to_cm) 

In [103]:
#changing weight from pounds to kg
data['Weight']=data['Weight'].str.replace('lbs','').astype(float)*0.45

In [104]:
# cleaning the money columns

money_columns = ["Value","Wage", "Release Clause"]
def money_in_numbers(value_str):
    # remove the euro symbol €
    value_str = value_str.replace("€","")
    
    #convert K and M to numerical equivalents
    if "K" in value_str:
        return float(value_str.replace("K","")) *1e3 # if is in the thousand ,replace K with empty space and multiply equivalent
    elif "M" in value_str:
        return float(value_str.replace("M","")) * 1e6 # if is milions ,replace M with empty space and multiply equivalent
    else:
        return float(value_str) #in case its already a number
    
for col in money_columns:
    data[col] = data[col].apply(money_in_numbers)


In [105]:
#drop NaN values in GK column
data.dropna(subset=['GK'], inplace=True)

In [106]:
#Deleting contract column
data=data.drop(columns=['Contract'],axis=1)

In [107]:
#cleaning Hits column
data['Hits'] =data['Hits'].apply(lambda x: float(x.replace('K',''))*1e3 if 'K' in str(x) else x)
data['Hits']= data['Hits'].astype(float)


In [108]:
position_columns = ['W/F', 'SM']
                     
for column in position_columns:
    data[column] = data[column].str.extract(r'(\d{1})').astype(object)

<span style="font-size: 200%;">X-Y Split</span>

In [109]:
#dropping the target to crrate a new subset X
X=data.drop('OVA', axis=1)     
y=data['OVA']

In [110]:
#Drop useless columns
X=X.drop(columns=['ID'],axis=1)
X=X.drop(columns=['Name'],axis=1)
X=X.drop(columns=['Team & Contract'],axis=1)

In [111]:
# separate numerical and categorical columns
X_num=X._get_numeric_data()
X_cat=X.drop(columns=X_num.columns)

print (X.shape, X_num.shape, X_cat.shape)  # check shape

(11641, 95) (11641, 84) (11641, 11)


In [112]:
#creating a correlation matrix
corr=X_num.corr()
corr

Age    Height    Weight    Growth     Value      Wage  \
Age     1.000000  0.093057  0.255369 -0.861718  0.099696  0.203139   
Height  0.093057  1.000000  0.767657 -0.053204 -0.002152  0.019469   
Weight  0.255369  0.767657  1.000000 -0.219783  0.035990  0.065521   
Growth -0.861718 -0.053204 -0.219783  1.000000 -0.186385 -0.236722   
Value   0.099696 -0.002152  0.035990 -0.186385  1.000000  0.819958   
...          ...       ...       ...       ...       ...       ...   
LCB     0.212120 -0.027082  0.017771 -0.264394  0.200220  0.215271   
CB      0.212120 -0.027082  0.017771 -0.264394  0.200220  0.215271   
RCB     0.212120 -0.027082  0.017771 -0.264394  0.200220  0.215271   
RB      0.154911 -0.237720 -0.181484 -0.244068  0.246304  0.240907   
GK      0.150727  0.348465  0.328231 -0.086450  0.045730  0.022892   

        Release Clause  Attacking  Crossing  Finishing  ...       LDM  \
Age           0.078812   0.192945  0.159120   0.110664  ...  0.228099   
Height       -0.002412  -0.351222 -0.490698  -0.356606  ... -0.177679   
Weight        0.028619  -0.251650 -0.391390  -0.263818  ... -0.112390   
Growth       -0.160353  -0.282449 -0.253248  -0.190287  ... -0.299356   
Value         0.978733   0.286480  0.249202   0.229465  ...  0.271639   
...                ...        ...       ...        ...  ...       ...   
LCB           0.192250   0.490389  0.496189   0.107210  ...  0.959209   
CB            0.192250   0.490389  0.496189   0.107210  ...  0.959209   
RCB           0.192250   0.490389  0.496189   0.107210  ...  0.959209   
RB            0.236141   0.646344  0.702550   0.289173  ...  0.980950   
GK            0.044458  -0.739918 -0.630468  -0.562008  ... -0.621562   

             CDM       RDM       RWB        LB       LCB        CB       RCB  \
Age     0.228099  0.228099  0.159220  0.154911  0.212120  0.212120  0.212120   
Height -0.177679 -0.177679 -0.298212 -0.237720 -0.027082 -0.027082 -0.027082   
Weight -0.112390 -0.112390 -0.230740 -0.181484  0.017771  0.017771  0.017771   
Growth -0.299356 -0.299356 -0.257474 -0.244068 -0.264394 -0.264394 -0.264394   
Value   0.271639  0.271639  0.269294  0.246304  0.200220  0.200220  0.200220   
...          ...       ...       ...       ...       ...       ...       ...   
LCB     0.959209  0.959209  0.909351  0.949769  1.000000  1.000000  1.000000   
CB      0.959209  0.959209  0.909351  0.949769  1.000000  1.000000  1.000000   
RCB     0.959209  0.959209  0.909351  0.949769  1.000000  1.000000  1.000000   
RB      0.980950  0.980950  0.991501  1.000000  0.949769  0.949769  0.949769   
GK     -0.621562 -0.621562 -0.693247 -0.667979 -0.565525 -0.565525 -0.565525   

              RB        GK  
Age     0.154911  0.150727  
Height -0.237720  0.348465  
Weight -0.181484  0.328231  
Growth -0.244068 -0.086450  
Value   0.246304  0.045730  
...          ...       ...  
LCB     0.949769 -0.565525  
CB      0.949769 -0.565525  
RCB     0.949769 -0.565525  
RB      1.000000 -0.667979  
GK     -0.667979  1.000000  

[84 rows x 84 columns]

In [113]:
import seaborn as sns
import matplotlib.pyplot as plt

In [114]:
# #creating a correlation heatmap
# fig, ax=plt.subplots(figsize=(50,50))
# ax=sns.heatmap(corr, annot=True)
# plt.show()

In [115]:
# np.fill
# mask = corr.abs().gt(0.9).any(axis=1)
# filtered_matrix=corr{mask}.loc[:,mask]

In [116]:
#Removing columns with correlations higher than 0.9
correlated_features = set()


for i in range(len(corr.columns)):
    for j in range(i):
        if abs(corr.iloc[i, j]) > 0.9:
            colname = corr.columns[i]
            correlated_features.add(colname)
            
X_num.drop(labels=correlated_features, axis=1, inplace=True)

len(correlated_features)
print(correlated_features)

{'LM', 'RAM', 'CM', 'LB', 'GK Positioning', 'RW', 'Positioning', 'RWB', 'Ball Control', 'ST', 'LW', 'RDM', 'GK Diving', 'GK Kicking', 'Skill', 'Sliding Tackle', 'Agility', 'RS', 'RM', 'Standing Tackle', 'LS', 'CB', 'GK Reflexes', 'DEF', 'GK Handling', 'Curve', 'LCM', 'GK', 'RF', 'RCM', 'LDM', 'Sprint Speed', 'LAM', 'Total Stats', 'Release Clause', 'LF', 'CAM', 'CDM', 'CF', 'Acceleration', 'LCB', 'Dribbling', 'RB', 'RCB', 'Marking', 'Defending'}


In [117]:
#removing columns which we suspect to overfit our data for the categorical values

X_cat =X_cat.drop('Nationality',axis=1)
X_cat =X_cat.drop('Club',axis=1)
X_cat =X_cat.drop('Joined',axis=1)
X_cat =X_cat.drop('Position',axis=1)
X_cat =X_cat.drop('foot',axis=1)


In [118]:
X_cat

BP W/F SM     A/W     D/W   IR
0       CM   4  2    High  Medium  1 ★
1       ST   3  4    High     Low  2 ★
2      CAM   4  4    High  Medium  2 ★
3      CDM   2  2  Medium  Medium  1 ★
4      CDM   2  3     Low  Medium  1 ★
...    ...  .. ..     ...     ...  ...
11695   ST   3  3    High     Low  1 ★
11696   LB   3  2  Medium  Medium  1 ★
11697   GK   2  1  Medium  Medium  1 ★
11698   RM   3  3    High  Medium  1 ★
11700  CAM   3  3    High     Low  1 ★

[11641 rows x 6 columns]

In [119]:
# #converting categorical data into numerical
# from sklearn.preprocessing import OneHotEncoder

# encoder = OneHotEncoder(drop='first').fit(X_cat)

# # Get the feature names
# encoded_categories = encoder.get_feature_names_out(input_features=X_cat.columns)

# # Transform the data and create a DataFrame with the feature names
# encoded = encoder.transform(X_cat).toarray()
# cat_encoded = pd.DataFrame(encoded, columns=encoded_categories)

# # cat_encoded.head(20)

In [120]:
#spliting nominal and ordinal data
from sklearn.preprocessing import OneHotEncoder

nominal_columns = ["BP"]
ordinal_columns = ["W/F","SM","A/W","D/W","IR"]

df_nominal = X_cat[nominal_columns]
df_ordinal = X_cat[ordinal_columns]

#encoding categorical variables
#fit and transform the nominal data
encoder = OneHotEncoder(drop="first").fit(df_nominal)  # no hay que volver a crearlo

encoded = encoder.transform(df_nominal).toarray()
print(encoded)
encoded_nominal_df=pd.DataFrame(encoded, columns = encoder.get_feature_names_out(nominal_columns))
encoded_nominal_df

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


BP_CB  BP_CDM  BP_CF  BP_CM  BP_GK  BP_LB  BP_LM  BP_LW  BP_LWB  BP_RB  \
0        0.0     0.0    0.0    1.0    0.0    0.0    0.0    0.0     0.0    0.0   
1        0.0     0.0    0.0    0.0    0.0    0.0    0.0    0.0     0.0    0.0   
2        0.0     0.0    0.0    0.0    0.0    0.0    0.0    0.0     0.0    0.0   
3        0.0     1.0    0.0    0.0    0.0    0.0    0.0    0.0     0.0    0.0   
4        0.0     1.0    0.0    0.0    0.0    0.0    0.0    0.0     0.0    0.0   
...      ...     ...    ...    ...    ...    ...    ...    ...     ...    ...   
11636    0.0     0.0    0.0    0.0    0.0    0.0    0.0    0.0     0.0    0.0   
11637    0.0     0.0    0.0    0.0    0.0    1.0    0.0    0.0     0.0    0.0   
11638    0.0     0.0    0.0    0.0    1.0    0.0    0.0    0.0     0.0    0.0   
11639    0.0     0.0    0.0    0.0    0.0    0.0    0.0    0.0     0.0    0.0   
11640    0.0     0.0    0.0    0.0    0.0    0.0    0.0    0.0     0.0    0.0   

       BP_RM  BP_RW  BP_RWB  BP_ST  
0        0.0    0.0     0.0    0.0  
1        0.0    0.0     0.0    1.0  
2        0.0    0.0     0.0    0.0  
3        0.0    0.0     0.0    0.0  
4        0.0    0.0     0.0    0.0  
...      ...    ...     ...    ...  
11636    0.0    0.0     0.0    1.0  
11637    0.0    0.0     0.0    0.0  
11638    0.0    0.0     0.0    0.0  
11639    1.0    0.0     0.0    0.0  
11640    0.0    0.0     0.0    0.0  

[11641 rows x 14 columns]

In [121]:
#encode ordinal data
from sklearn.preprocessing import OrdinalEncoder 
#we should make sure that we have the order that we want
wf_mapping = ['1', '2', '3', '4', '5']
sm_mapping = ['1', '2', '3', '4', '5'] 
ir_mapping = ['1 ★', '2 ★', '3 ★', '4 ★', '5 ★']
aw_mapping = ['Low', 'Medium', 'High']
dw_mapping = ['Low', 'Medium', 'High']

# Combine the mappings into a list
mappings = [wf_mapping, sm_mapping, aw_mapping, dw_mapping, ir_mapping]

# Create the encoder
encoder = OrdinalEncoder(categories=mappings)

# Fit and transform the data
df_ordinal_encoded = encoder.fit_transform(X_cat[['W/F', 'SM', 'A/W', 'D/W', 'IR']])

# Convert the result back to a DataFrame
df_ordinal_encoded = pd.DataFrame(df_ordinal_encoded, columns=['W/F', 'SM', 'A/W', 'D/W', 'IR'])


In [122]:
#import modules
from sklearn.preprocessing import MinMaxScaler # do not use the function Normalise() - it does something entirely different
from sklearn.preprocessing import StandardScaler

#Scale the numerical data
transformer = MinMaxScaler().fit(X_num)
x_normalized = transformer.transform(X_num)
print(x_normalized.shape)
x_normalized
x_normalized=pd.DataFrame(x_normalized, columns=X_num.columns)

(11641, 38)


In [123]:
#merging numerical and categorical data
X=pd.concat([x_normalized, df_ordinal_encoded,encoded_nominal_df], axis=1) 

In [124]:
# LINEAR REGRESSION

#import libraries
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error, r2_score

#train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

lm = linear_model.LinearRegression()
lm.fit(X_train,y_train)

predictions = lm.predict(X_train)
r2_y_train=r2_score(y_train, predictions)

predictions_test = lm.predict(X_test)
r2_score(y_test, predictions_test)

mse = mean_squared_error(y_test,predictions_test)
print('The mean squared error is: ' + str(mse))

rmse = np.sqrt(mean_squared_error(y_test,predictions_test))
print('The root mean squared error is: ' + str(rmse))

mae = mean_absolute_error(y_test, predictions_test)
print('The mean absolute error is: ' + str(mae))

r2 = r2_score(y_test, predictions_test)
print(('The r squared value is: ' + str(r2)))

(10476, 57)
(1165, 57)
(10476,)
(1165,)
The mean squared error is: 3.69222870609791
The root mean squared error is: 1.9215172926877109
The mean absolute error is: 1.4776329466201716
The r squared value is: 0.9227377440989492


<span style="font-size: 200%;">Validating Our Model</span>

In [125]:
#Import validation data
data_validate = pd.read_csv('fifa21_validate.csv')
data_validate

ID             Name  Age    Nationality                    Club  \
0     219461  E. Palmer-Brown   23  United States         FK Austria Wien   
1     221896       D. Avdijaj   22         Kosovo     Heart of Midlothian   
2     247428         D. Ochoa   19  United States          Real Salt Lake   
3     255120        N. Kenneh   16        England            Leeds United   
4     215556     E. Fernandes   24    Switzerland         1. FSV Mainz 05   
...      ...              ...  ...            ...                     ...   
1994  239074            S. Aw   21        Senegal          Gil Vicente FC   
1995  241223          S. Mogi   21          Japan            Cerezo Osaka   
1996  210930       Carles Gil   27          Spain  New England Revolution   
1997  162993         J. Perch   34        England          Mansfield Town   
1998  254882    A. Oeynhausen   18        Germany         SC Paderborn 07   

       BP   Position                       Team & Contract Height  Weight  \
0      CB         CB  FK Austria Wien Jun 30, 2021 On Loan   6'2"  194lbs   
1     CAM     LM CAM       Heart of Midlothian 2020 ~ 2020   5'8"  154lbs   
2      GK         GK            Real Salt Lake 2018 ~ 2020   6'2"  176lbs   
3     CDM  CB CDM RB              Leeds United 2020 ~ 2022   6'3"  170lbs   
4     CDM     CM CDM           1. FSV Mainz 05 2019 ~ 2023   6'2"  170lbs   
...   ...        ...                                   ...    ...     ...   
1994   LB         LB            Gil Vicente FC 2020 ~ 2023   5'8"  143lbs   
1995   GK         GK              Cerezo Osaka 2017 ~ 2021   6'5"  176lbs   
1996   RM  RM CAM CM    New England Revolution 2019 ~ 2024   5'7"  146lbs   
1997  CDM  CDM RB CM            Mansfield Town 2020 ~ 2021  5'11"  176lbs   
1998  CAM         CM           SC Paderborn 07 2020 ~ 2022  5'10"  150lbs   

      ...   CDM   RDM   RWB    LB   LCB    CB   RCB    RB    GK  OVA  
0     ...  61+2  61+2  59+2  61+2  67+2  67+2  67+2  61+2  16+2   67  
1     ...  47+2  47+2  49+2  45+2  38+2  38+2  38+2  45+2  17+2   68  
2     ...  18+2  18+2  16+2  16+2  18+2  18+2  18+2  16+2  53+2   54  
3     ...  54+2  54+2  53+2  53+2  54+2  54+2  54+2  53+2  11+2   55  
4     ...  72+2  72+2  70+2  69+2  68+2  68+2  68+2  69+2  18+2   70  
...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...  
1994  ...  52+2  52+2  58+2  58+2  54+2  54+2  54+2  58+2  15+2   60  
1995  ...  23+2  23+2  20+2  20+2  22+2  22+2  22+2  20+2  58+2   59  
1996  ...  60+2  60+2  62+2  57+2  47+2  47+2  47+2  57+2  18+2   76  
1997  ...  62+1  62+1  60+2  60+2  63+0  63+0  63+0  60+2  14+2   63  
1998  ...  55+2  55+2  55+2  54+2  51+2  51+2  51+2  54+2  16+2   60  

[1999 rows x 101 columns]

In [126]:
#filling in the average composure of each player. NaN is replaces with the mean value of players who play in the same position. (mean is categorised into each position, players who play in the same BP, then the composure of those is calculated and used to replace the NaN values )
data_validate['Composure'] = data_validate.groupby('BP')['Composure'].transform(lambda x: x.fillna(x.mean()))

#checking for nan values
nan_counts = data_validate.isna().sum()

nan_columns = nan_counts[nan_counts>0]
nan_columns

Club                 3
Position            55
Joined               3
Loan Date End     1889
Volleys              3
Curve                3
Agility              3
Balance              3
Jumping              3
Vision               3
Sliding Tackle       3
A/W                  8
D/W                  8
dtype: int64

In [127]:
#Specifying which columns to keep so they are equililent to the ones used in the model
columns_to_keep = ['Age', 'Height', 'Weight', 'Growth', 'Value', 'Wage', 'Attacking', 'Crossing', 'Finishing', 'Heading Accuracy', 'Short Passing', 'Volleys', 'FK Accuracy', 'Long Passing', 'Movement', 'Reactions', 'Balance', 'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots', 'Mentality', 'Aggression', 'Interceptions', 'Vision', 'Penalties', 'Composure', 'Goalkeeping', 'Base Stats', 'PAC', 'SHO', 'PAS', 'DRI', 'PHY', 'Hits', 'LWB', 'BP', 'W/F', 'SM', 'A/W', 'D/W', 'IR','OVA']

data_validate2 = data_validate[columns_to_keep].copy()

In [128]:
#checking fro nan values
nan_counts = data_validate2.isna().sum()
nan_columns = nan_counts[nan_counts>0]
nan_columns

Volleys    3
Balance    3
Jumping    3
Vision     3
A/W        8
D/W        8
dtype: int64

In [129]:
#dropping NaN values in the A/W column
data_validate2.dropna(subset = ['A/W'], inplace=True)

#checking fro nan values
nan_counts = data_validate2.isna().sum()
nan_columns = nan_counts[nan_counts>0]
nan_columns

Series([], dtype: int64)

In [130]:
data_validate2

Age Height  Weight  Growth  Value  Wage  Attacking  Crossing  Finishing  \
0      23   6'2"  194lbs       7  €975K   €5K        230        47         21   
1      22   5'8"  154lbs       5  €1.2M   €3K        298        62         60   
2      19   6'2"  176lbs      17  €120K  €500         48         7          5   
3      16   6'3"  170lbs      23  €160K  €500        215        38         31   
4      24   6'2"  170lbs       5  €2.3M  €13K        295        57         59   
...   ...    ...     ...     ...    ...   ...        ...       ...        ...   
1994   21   5'8"  143lbs      11  €325K   €1K        197        59         23   
1995   21   6'5"  176lbs       9  €190K  €700         77        13          9   
1996   27   5'7"  146lbs       0    €8M   €9K        332        76         72   
1997   34  5'11"  176lbs       0  €140K   €4K        268        58         44   
1998   18  5'10"  150lbs      16  €425K   €1K        276        49         54   

      Heading Accuracy  ...  PHY  Hits   LWB   BP  W/F  SM     A/W     D/W  \
0                   62  ...   74    34  59+2   CB  2 ★  2★     Low    High   
1                   44  ...   57    12  49+2  CAM  4 ★  3★    High     Low   
2                   11  ...   53     3  16+2   GK  2 ★  1★  Medium  Medium   
3                   55  ...   59     6  53+2  CDM  3 ★  2★  Medium  Medium   
4                   45  ...   71    45  70+2  CDM  4 ★  2★  Medium  Medium   
...                ...  ...  ...   ...   ...  ...  ...  ..     ...     ...   
1994                42  ...   57     4  58+2   LB  3 ★  2★    High  Medium   
1995                14  ...   54     3  20+2   GK  2 ★  1★  Medium  Medium   
1996                34  ...   60    15  62+2   RM  4 ★  4★    High  Medium   
1997                61  ...   69     4  60+2  CDM  3 ★  2★  Medium  Medium   
1998                51  ...   47     5  55+2  CAM  3 ★  2★  Medium  Medium   

       IR  OVA  
0     1 ★   67  
1     1 ★   68  
2     1 ★   54  
3     1 ★   55  
4     1 ★   70  
...   ...  ...  
1994  1 ★   60  
1995  1 ★   59  
1996  2 ★   76  
1997  1 ★   63  
1998  1 ★   60  

[1991 rows x 45 columns]

In [131]:
# replaing + - signs in columns

position_columns = ['LWB']
for column in position_columns:
    data_validate2[column] = data_validate2[column].str.extract(r'(\d{2})').astype(float)

In [132]:
#changing the height from ft and inches to cm

data_validate2['Height'] =data_validate2['Height'].apply(height_to_cm) 

In [133]:
#changing the weight from poundsto kg
data_validate2['Weight']=data_validate2['Weight'].str.replace('lbs','').astype(float)*0.45

In [134]:
money_columns=data_validate2[['Value','Wage']]

for col in money_columns:
    data_validate2[col] = data_validate2[col].apply(money_in_numbers)

In [135]:
data_validate2[['Value','Wage']].dtypes

Value    float64
Wage     float64
dtype: object

In [136]:
#cleaning Hits column
data_validate2['Hits'] =data_validate2['Hits'].apply(lambda x: float(x.replace('K',''))*1e3 if 'K' in str(x) else x)
data_validate2['Hits']= data_validate2['Hits'].astype(float)

In [137]:
#dropping the target to crrate a new subset X
X_v=data_validate2.drop('OVA', axis=1)     
y_v=data_validate2['OVA']

In [138]:
# separate numerical and categorical columns
X_for_p_num = X_v.select_dtypes(include = np.number)
X_for_p_cat = X_v.select_dtypes(include = object)

In [139]:
X_num.dtypes


Age                   int64
Height              float64
Weight              float64
Growth                int64
Value               float64
Wage                float64
Attacking             int64
Crossing              int64
Finishing             int64
Heading Accuracy      int64
Short Passing         int64
Volleys             float64
FK Accuracy           int64
Long Passing          int64
Movement              int64
Reactions             int64
Balance             float64
Power                 int64
Shot Power            int64
Jumping             float64
Stamina               int64
Strength              int64
Long Shots            int64
Mentality             int64
Aggression            int64
Interceptions       float64
Vision              float64
Penalties             int64
Composure           float64
Goalkeeping           int64
Base Stats            int64
PAC                   int64
SHO                   int64
PAS                   int64
DRI                   int64
PHY                 

In [140]:
X_for_p_num.dtypes

Age                   int64
Height              float64
Weight              float64
Growth                int64
Value               float64
Wage                float64
Attacking             int64
Crossing              int64
Finishing             int64
Heading Accuracy      int64
Short Passing         int64
Volleys             float64
FK Accuracy           int64
Long Passing          int64
Movement              int64
Reactions             int64
Balance             float64
Power                 int64
Shot Power            int64
Jumping             float64
Stamina               int64
Strength              int64
Long Shots            int64
Mentality             int64
Aggression            int64
Interceptions       float64
Vision              float64
Penalties             int64
Composure           float64
Goalkeeping           int64
Base Stats            int64
PAC                   int64
SHO                   int64
PAS                   int64
DRI                   int64
PHY                 

In [141]:
X_for_p_normalized = transformer.transform(X_for_p_num)
X_for_p_normalized = pd.DataFrame(X_for_p_normalized,columns=X_for_p_num.columns)

In [142]:
X_for_p_normalized

Age  Height    Weight    Growth     Value      Wage  Attacking  \
0     0.259259    0.65  0.611111  0.269231  0.010833  0.008929   0.475949   
1     0.222222    0.35  0.293651  0.192308  0.013333  0.005357   0.648101   
2     0.111111    0.65  0.468254  0.653846  0.001333  0.000893   0.015190   
3     0.000000    0.70  0.420635  0.884615  0.001778  0.000893   0.437975   
4     0.296296    0.65  0.420635  0.192308  0.025556  0.023214   0.640506   
...        ...     ...       ...       ...       ...       ...        ...   
1986  0.185185    0.35  0.206349  0.423077  0.003611  0.001786   0.392405   
1987  0.185185    0.80  0.468254  0.346154  0.002111  0.001250   0.088608   
1988  0.407407    0.30  0.230159  0.000000  0.088889  0.016071   0.734177   
1989  0.666667    0.50  0.468254  0.000000  0.001556  0.007143   0.572152   
1990  0.074074    0.45  0.261905  0.615385  0.004722  0.001786   0.592405   

      Crossing  Finishing  Heading Accuracy  ...  Composure  Goalkeeping  \
0     0.465909   0.195652          0.647727  ...   0.440476     0.103044   
1     0.636364   0.619565          0.443182  ...   0.630952     0.096019   
2     0.011364   0.021739          0.068182  ...   0.226190     0.601874   
3     0.363636   0.304348          0.568182  ...   0.559524     0.056206   
4     0.579545   0.608696          0.454545  ...   0.607143     0.112412   
...        ...        ...               ...  ...        ...          ...   
1986  0.602273   0.217391          0.420455  ...   0.559524     0.091335   
1987  0.079545   0.065217          0.102273  ...   0.250000     0.646370   
1988  0.795455   0.750000          0.329545  ...   0.750000     0.107728   
1989  0.590909   0.445652          0.636364  ...   0.571429     0.072600   
1990  0.488636   0.554348          0.522727  ...   0.630952     0.105386   

      Base Stats       PAC       SHO       PAS       DRI       PHY      Hits  \
0       0.404580  0.542857  0.171053  0.367647  0.328358  0.734375  0.003371   
1       0.496183  0.685714  0.657895  0.544118  0.686567  0.468750  0.000979   
2       0.255725  0.428571  0.460526  0.411765  0.402985  0.406250  0.000000   
3       0.286260  0.457143  0.223684  0.323529  0.358209  0.500000  0.000326   
4       0.683206  0.585714  0.592105  0.632353  0.626866  0.687500  0.004567   
...          ...       ...       ...       ...       ...       ...       ...   
1986    0.332061  0.714286  0.144737  0.308824  0.402985  0.468750  0.000109   
1987    0.343511  0.485714  0.500000  0.470588  0.507463  0.421875  0.000000   
1988    0.610687  0.557143  0.684211  0.779412  0.731343  0.515625  0.001305   
1989    0.450382  0.385714  0.394737  0.485294  0.447761  0.656250  0.000109   
1990    0.423664  0.542857  0.486842  0.544118  0.507463  0.312500  0.000217   

           LWB  
0     0.642857  
1     0.500000  
2     0.028571  
3     0.557143  
4     0.800000  
...        ...  
1986  0.628571  
1987  0.085714  
1988  0.685714  
1989  0.657143  
1990  0.585714  

[1991 rows x 38 columns]

In [143]:
X_for_p_cat

BP  W/F  SM     A/W     D/W   IR
0      CB  2 ★  2★     Low    High  1 ★
1     CAM  4 ★  3★    High     Low  1 ★
2      GK  2 ★  1★  Medium  Medium  1 ★
3     CDM  3 ★  2★  Medium  Medium  1 ★
4     CDM  4 ★  2★  Medium  Medium  1 ★
...   ...  ...  ..     ...     ...  ...
1994   LB  3 ★  2★    High  Medium  1 ★
1995   GK  2 ★  1★  Medium  Medium  1 ★
1996   RM  4 ★  4★    High  Medium  2 ★
1997  CDM  3 ★  2★  Medium  Medium  1 ★
1998  CAM  3 ★  2★  Medium  Medium  1 ★

[1991 rows x 6 columns]

In [144]:
# one hot encoding
#spliting nominal and ordinal data
nominal_columns_validate = ["BP"]
ordinal_columns_validate = ["W/F","SM","A/W","D/W","IR"]

df_nominal_validate = X_for_p_cat[nominal_columns_validate]
df_ordinal_validate = X_for_p_cat[ordinal_columns_validate]

In [145]:
encoder_validate = OneHotEncoder(drop="first").fit(df_nominal)  
encoded_validate = encoder_validate.transform(df_nominal_validate).toarray()
print(encoded_validate)
encoded_nominal_df_validate=pd.DataFrame(encoded_validate, columns = encoder_validate.get_feature_names_out(nominal_columns_validate))
encoded_nominal_df_validate

[[1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


BP_CB  BP_CDM  BP_CF  BP_CM  BP_GK  BP_LB  BP_LM  BP_LW  BP_LWB  BP_RB  \
0       1.0     0.0    0.0    0.0    0.0    0.0    0.0    0.0     0.0    0.0   
1       0.0     0.0    0.0    0.0    0.0    0.0    0.0    0.0     0.0    0.0   
2       0.0     0.0    0.0    0.0    1.0    0.0    0.0    0.0     0.0    0.0   
3       0.0     1.0    0.0    0.0    0.0    0.0    0.0    0.0     0.0    0.0   
4       0.0     1.0    0.0    0.0    0.0    0.0    0.0    0.0     0.0    0.0   
...     ...     ...    ...    ...    ...    ...    ...    ...     ...    ...   
1986    0.0     0.0    0.0    0.0    0.0    1.0    0.0    0.0     0.0    0.0   
1987    0.0     0.0    0.0    0.0    1.0    0.0    0.0    0.0     0.0    0.0   
1988    0.0     0.0    0.0    0.0    0.0    0.0    0.0    0.0     0.0    0.0   
1989    0.0     1.0    0.0    0.0    0.0    0.0    0.0    0.0     0.0    0.0   
1990    0.0     0.0    0.0    0.0    0.0    0.0    0.0    0.0     0.0    0.0   

      BP_RM  BP_RW  BP_RWB  BP_ST  
0       0.0    0.0     0.0    0.0  
1       0.0    0.0     0.0    0.0  
2       0.0    0.0     0.0    0.0  
3       0.0    0.0     0.0    0.0  
4       0.0    0.0     0.0    0.0  
...     ...    ...     ...    ...  
1986    0.0    0.0     0.0    0.0  
1987    0.0    0.0     0.0    0.0  
1988    1.0    0.0     0.0    0.0  
1989    0.0    0.0     0.0    0.0  
1990    0.0    0.0     0.0    0.0  

[1991 rows x 14 columns]

In [146]:
#encode ordinal data
#we should make sure that we have the order that we want
wf_mapping_validate = ['1 ★', '2 ★', '3 ★', '4 ★', '5 ★']
sm_mapping_validate = ['1★', '2★', '3★', '4★', '5★'] 
ir_mapping_validate = ['1 ★', '2 ★', '3 ★', '4 ★', '5 ★']
aw_mapping_validate = ['Low', 'Medium', 'High']
dw_mapping_validate = ['Low', 'Medium', 'High']

# Combine the mappings into a list
mappings_validate = [wf_mapping_validate, sm_mapping_validate, aw_mapping_validate, dw_mapping_validate, ir_mapping_validate]

# Create the encoder
encoder_validate = OrdinalEncoder(categories=mappings_validate)

# Fit and transform the data
df_ordinal_encoded_validate = encoder_validate.fit_transform(X_for_p_cat[['W/F', 'SM', 'A/W', 'D/W', 'IR']])

# Convert the result back to a DataFrame
df_ordinal_encoded_validate = pd.DataFrame(df_ordinal_encoded_validate, columns=['W/F', 'SM', 'A/W', 'D/W', 'IR'])
df_ordinal_encoded_validate

W/F   SM  A/W  D/W   IR
0     1.0  1.0  0.0  2.0  0.0
1     3.0  2.0  2.0  0.0  0.0
2     1.0  0.0  1.0  1.0  0.0
3     2.0  1.0  1.0  1.0  0.0
4     3.0  1.0  1.0  1.0  0.0
...   ...  ...  ...  ...  ...
1986  2.0  1.0  2.0  1.0  0.0
1987  1.0  0.0  1.0  1.0  0.0
1988  3.0  3.0  2.0  1.0  1.0
1989  2.0  1.0  1.0  1.0  0.0
1990  2.0  1.0  1.0  1.0  0.0

[1991 rows x 5 columns]

In [149]:
X_for_p = pd.concat([X_for_p_normalized,df_ordinal_encoded_validate,encoded_nominal_df_validate], axis=1)
X_for_p

Age  Height    Weight    Growth     Value      Wage  Attacking  \
0     0.259259    0.65  0.611111  0.269231  0.010833  0.008929   0.475949   
1     0.222222    0.35  0.293651  0.192308  0.013333  0.005357   0.648101   
2     0.111111    0.65  0.468254  0.653846  0.001333  0.000893   0.015190   
3     0.000000    0.70  0.420635  0.884615  0.001778  0.000893   0.437975   
4     0.296296    0.65  0.420635  0.192308  0.025556  0.023214   0.640506   
...        ...     ...       ...       ...       ...       ...        ...   
1986  0.185185    0.35  0.206349  0.423077  0.003611  0.001786   0.392405   
1987  0.185185    0.80  0.468254  0.346154  0.002111  0.001250   0.088608   
1988  0.407407    0.30  0.230159  0.000000  0.088889  0.016071   0.734177   
1989  0.666667    0.50  0.468254  0.000000  0.001556  0.007143   0.572152   
1990  0.074074    0.45  0.261905  0.615385  0.004722  0.001786   0.592405   

      Crossing  Finishing  Heading Accuracy  ...  BP_GK  BP_LB  BP_LM  BP_LW  \
0     0.465909   0.195652          0.647727  ...    0.0    0.0    0.0    0.0   
1     0.636364   0.619565          0.443182  ...    0.0    0.0    0.0    0.0   
2     0.011364   0.021739          0.068182  ...    1.0    0.0    0.0    0.0   
3     0.363636   0.304348          0.568182  ...    0.0    0.0    0.0    0.0   
4     0.579545   0.608696          0.454545  ...    0.0    0.0    0.0    0.0   
...        ...        ...               ...  ...    ...    ...    ...    ...   
1986  0.602273   0.217391          0.420455  ...    0.0    1.0    0.0    0.0   
1987  0.079545   0.065217          0.102273  ...    1.0    0.0    0.0    0.0   
1988  0.795455   0.750000          0.329545  ...    0.0    0.0    0.0    0.0   
1989  0.590909   0.445652          0.636364  ...    0.0    0.0    0.0    0.0   
1990  0.488636   0.554348          0.522727  ...    0.0    0.0    0.0    0.0   

      BP_LWB  BP_RB  BP_RM  BP_RW  BP_RWB  BP_ST  
0        0.0    0.0    0.0    0.0     0.0    0.0  
1        0.0    0.0    0.0    0.0     0.0    0.0  
2        0.0    0.0    0.0    0.0     0.0    0.0  
3        0.0    0.0    0.0    0.0     0.0    0.0  
4        0.0    0.0    0.0    0.0     0.0    0.0  
...      ...    ...    ...    ...     ...    ...  
1986     0.0    0.0    0.0    0.0     0.0    0.0  
1987     0.0    0.0    0.0    0.0     0.0    0.0  
1988     0.0    0.0    1.0    0.0     0.0    0.0  
1989     0.0    0.0    0.0    0.0     0.0    0.0  
1990     0.0    0.0    0.0    0.0     0.0    0.0  

[1991 rows x 57 columns]

In [ ]:
#APPLY THE MODEL

In [150]:
results_for_validate = lm.predict(X_for_p)
comparision= pd.concat([X_for_p,pd.Series(results_for_validate, name='estimate')],axis=1).head()
comparision

Age  Height    Weight    Growth     Value      Wage  Attacking  \
0  0.259259    0.65  0.611111  0.269231  0.010833  0.008929   0.475949   
1  0.222222    0.35  0.293651  0.192308  0.013333  0.005357   0.648101   
2  0.111111    0.65  0.468254  0.653846  0.001333  0.000893   0.015190   
3  0.000000    0.70  0.420635  0.884615  0.001778  0.000893   0.437975   
4  0.296296    0.65  0.420635  0.192308  0.025556  0.023214   0.640506   

   Crossing  Finishing  Heading Accuracy  ...  BP_LB  BP_LM  BP_LW  BP_LWB  \
0  0.465909   0.195652          0.647727  ...    0.0    0.0    0.0     0.0   
1  0.636364   0.619565          0.443182  ...    0.0    0.0    0.0     0.0   
2  0.011364   0.021739          0.068182  ...    0.0    0.0    0.0     0.0   
3  0.363636   0.304348          0.568182  ...    0.0    0.0    0.0     0.0   
4  0.579545   0.608696          0.454545  ...    0.0    0.0    0.0     0.0   

   BP_RB  BP_RM  BP_RW  BP_RWB  BP_ST   estimate  
0    0.0    0.0    0.0     0.0    0.0  65.203125  
1    0.0    0.0    0.0     0.0    0.0  65.868164  
2    0.0    0.0    0.0     0.0    0.0  53.441406  
3    0.0    0.0    0.0     0.0    0.0  56.581055  
4    0.0    0.0    0.0     0.0    0.0  69.678711  

[5 rows x 58 columns]

In [153]:
# LINEAR REGRESSION

#import libraries
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error, r2_score

mse = mean_squared_error(y_v,results_for_validate)
print('The mean squared error is: ' + str(mse))

rmse = np.sqrt(mean_squared_error(y_v,results_for_validate))
print('The root mean squared error is: ' + str(rmse))

mae = mean_absolute_error(y_v, results_for_validate)
print('The mean absolute error is: ' + str(mae))

r2 = r2_score(y_v, results_for_validate)
print(('The r squared value is: ' + str(r2)))

The mean squared error is: 4.038018744414563
The root mean squared error is: 2.0094822080363297
The mean absolute error is: 1.5528795595806129
The r squared value is: 0.9114742084519516
